<?php

namespace app\modules\admin\controllers;

use app\support\filter\LoginFilter;

class BaseController extends \app\controllers\BaseController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        
    }

    /**
     * 追加行为
     * @return array
     * @author: liuFangShuo
     */
    public function appendBehaviors()
    {
        return [];
    }

    /**
     * 行为
     * @return array
     * @author: liuFangShuo
     */
    public function behaviors()
    {

        $default = [
            'login' => [
                'class' =>LoginFilter::className(),
                'failUrl' => '/login'
            ]
        ];
        $append = $this->appendBehaviors();

        return array_merge($default,$append);
    }



}
