<?php

namespace app\modules\admin\controllers;
use yii\web\Controller;

class BaseController extends Controller
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        
    }

    /**
     * 追加行为
     * @return array
     * @author: liuFangShuo
     */
    public function appendBehaviors()
    {
        return [];
    }

    /**
     * 行为
     * @return array
     * @author: liuFangShuo
     */
    public function behaviors()
    {
        $parent = parent::behaviors(); // TODO: Change the autogenerated stub

        $default = [];

        $append = $this->appendBehaviors();

        return array_merge($parent,$default,$append);
    }



}
