<?php

namespace app\modules\admin\controllers;

use app\support\filter\LoginFilter;
use app\controllers\BasicController;

class BaseController extends BasicController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }


    /**
     * 行为
     * @return array
     * @author: liuFangShuo
     */
    public function behaviors()
    {

        //登录中间件
        $default = [
            'login' => [
                'class' => LoginFilter::className(),
                'failUrl' => '/login'
            ]
        ];
        $append = $this->appendBehaviors();

        return array_merge($default,$append);
    }
    
}
