<?php
/**
 * Created by liuFangShuo.
 * User: lfs
 * Date: 2017/4/13
 * Time: 09:34
 */

namespace app\controllers;
use app\models\CategoryAR;
use app\models\CompanyModel;
use app\models\ConfigModel;
use yii\base\Exception;

class BaseController extends BasicController
{
    
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        //获取配置
        $configModel = new ConfigModel();
        $config = $configModel->getConfig(['id' => 1]);

        if(empty($config) || $config->open == STATUS_FALSE){
            throw new Exception('网站已关闭！！！');
        }
        $this->view->params['config'] = $config;


        //获取分类
        $categoryModel = new CategoryAR();
        $categoryListArr = $categoryModel->getCategoryList(false, ['pid'=>SORT_ASC, 'sort' => SORT_ASC]);
        $categoryList = [];

        if(!empty($categoryListArr)){
            foreach ($categoryListArr as $key => $value) {
                if($value->pid == 0){
                    $categoryList[$value->id] = $value->toArray();
                } else {
                    $categoryList[$value->pid]['son'][$value->id] =$value->toArray();
                }
            }
        }

        $this->view->params['category'] = $categoryList;

        //获取主要公司地址
        $addressModel = new CompanyModel();
        $adress = $addressModel->getMainCompany();
        $this->view->params['mainAddress'] = $adress;

    }

    /**
     * 追加行为
     * @return array
     * @author: liuFangShuo
     */
    public function appendBehaviors()
    {
        return [];
    }
    
}