<?php
/**
 * Created by liuFangShuo.
 * User: lfs
 * Date: 2017/6/15
 * Time: 16:40
 */

namespace app\controllers;

use yii\web\Response;
use yii\web\Controller;

class BasicController extends Controller
{
    protected $_data = null;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * 追加行为
     * @return array
     * @author: liuFangShuo
     */
    public function appendBehaviors()
    {
        return [];
    }

    /**
     * 行为
     * @return array
     * @author: liuFangShuo
     */
    public function behaviors()
    {
        $parent = parent::behaviors(); // TODO: Change the autogenerated stub

        $default = [];

        $append = $this->appendBehaviors();

        return array_merge($parent,$default,$append);
    }


    protected function ajaxReturn($data = array(), $code = 0, $message = '')
    {
        $data = array(
            'data' => $data,
            'code' => $code,
            'message' => $message
        );

        return \Yii::createObject([
            'class' => 'yii\web\Response',
            'format' => Response::FORMAT_JSON,
            'data' => $data
        ]);
    }
}