<?php
/**
 * Created by liuFangShuo.
 * User: lfs
 * Date: 2017/6/16
 * Time: 14:15
 */

namespace app\models;


use yii\base\Model;

class CompanyModel extends Model
{
    private $company = false;

    public $id;
    public $address;
    public $localtion;
    public $description;
    public $name;
    public $qq;
    public $phone;
    public $email;
    public $city;

    
    
    public function rules()
    {
        $rules = parent::rules(); // TODO: Change the autogenerated stub
        $rule = [
            [['address', 'name', 'qq', 'phone', 'localtion', 'city'], 'required', 'message' => '此选项不能为空'],
            ['email', 'email', 'message' => '请输入正确的邮箱'],
            ['email', 'default', 'value' => ''],
            [['description','id'] ,'safe']
        ];

        return array_merge($rules,$rule);
    }
    
    public function insertInfo()
    {
        $model = new AboutAR();
        $model->load($this->attributes,'');

        $model->is_deleted = STATUS_FALSE;
        $model->level = STATUS_FALSE;

        if ($model->insert(false)) {
            return true;
        } else {
            var_dump($model->getFirstErrors());exit;
        }
    }

    /**
     * 获取公司地址
     * @param int $num
     * @param array $order
     * @return array|\yii\db\ActiveRecord[]
     * @author: liuFangShuo
     */
    public function getCompanyList($num = 0, $order = ['level' => SORT_DESC, 'create_time' => SORT_DESC])
    {
        $model = new AboutAR();
        $sql = $model->find()->where(['is_deleted' => STATUS_FALSE])->orderBy($order);

        if ($num > 0) {
            $sql->limit($num);
        }

        return $sql->asArray()->all();
    }
    
}